# Generated by Django 4.2.20 on 2025-04-03 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentorados', '0002_disponibilidadehorario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadehorario',
            name='init_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data inicial'),
        ),
        migrations.AlterField(
            model_name='disponibilidadehorario',
            name='is_scheduled',
            field=models.BooleanField(default=False, verbose_name='Está agendado'),
        ),
        migrations.AlterField(
            model_name='disponibilidadehorario',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Mentor'),
        ),
    ]
