# Generated by Django 4.2.20 on 2025-04-03 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentorados', '0003_alter_disponibilidadehorario_init_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorado',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='mentorado',
            name='navigator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mentorados.navigator', verbose_name='Navigator'),
        ),
        migrations.AlterField(
            model_name='mentorado',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='mentorado',
            name='stage',
            field=models.CharField(choices=[('E1', '10-100k'), ('E2', '100-500k'), ('E3', '500-...')], max_length=2, verbose_name='Estágio'),
        ),
        migrations.AlterField(
            model_name='mentorado',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Mentor'),
        ),
        migrations.AlterField(
            model_name='navigator',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='navigator',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='navigator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Mentor'),
        ),
    ]
