# Generated by Django 4.2.20 on 2025-04-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorados', '0004_alter_mentorado_name_alter_mentorado_navigator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disponibilidadehorario',
            options={'verbose_name': 'Disponibilidade de Horário', 'verbose_name_plural': 'Disponibilidade de Horários'},
        ),
        migrations.AlterModelOptions(
            name='mentorado',
            options={'verbose_name': 'Mentorado', 'verbose_name_plural': 'Mentorados'},
        ),
        migrations.AlterModelOptions(
            name='navigator',
            options={'verbose_name': 'Navigator', 'verbose_name_plural': 'Navigators'},
        ),
        migrations.AddField(
            model_name='mentorado',
            name='token',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
