# Generated by Django 4.2.20 on 2025-04-04 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentorados', '0005_alter_disponibilidadehorario_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('G', 'Gestão'), ('M', 'Marketing'), ('RH', 'Gestão de Pessoas'), ('I', 'Impostos')], max_length=2, verbose_name='Tag')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorados.disponibilidadehorario', verbose_name='Data')),
                ('mentorado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentorados.mentorado', verbose_name='Mentorado')),
            ],
            options={
                'verbose_name': 'Reunião',
                'verbose_name_plural': 'Reuniões',
            },
        ),
    ]
